const Diseasedb = [
   {
     imgsource: require("../assets/Disease/acidity.png"),
     engName: "Acidity",
     translations: {
       russian: "Кислотность",
       hindi: "अम्लता",
       german: "Säure",
       punjabi: "ਐਸੀਡਿਟੀ",
       tamil: "சுருக்கம்",
       bengali: "অম্লতা",
       gujrati: "એસિડિટી",
       kannada: "ಆಮ್ಲತಾ",
       urdu: "تیزابیت",
       malayalam: "ആമ്ലത",
       french: "Acidité",
       spanish: "Acidez",
       dutch: "Zuurgraad",
       portuguese: "Acidez",
       telugu: "ఆమ్లత",
       select: "",
     },
   },
   {
     imgsource: require("../assets/Disease/freezing.png"),
     engName: "Freezing",
     translations: {
       russian: "холод",
       hindi: "थंड लगना",
       german: "Kalt",
       punjabi: "ਠੰਡ ਲੱਗਣਾ",
       tamil: "புதியவருக்கு அதிகம் செய்வது",
       bengali: "মুক্তস্পৃশ",
       gujrati: "ફ્રીઝિંગ",
       kannada: "ಮೂಳೆ",
       urdu: "جما دینا",
       malayalam: "മനുഷ്യർക്ക് നേരത്തെ",
       french: "Congélation",
       spanish: "Congelación",
       dutch: "Bevriezen",
       portuguese: "Congelamento",
       telugu: "ఉదయం",
     },
   },
   {
     imgsource: require("../assets/Disease/coughing.png"),
     engName: "Coughing",
     translations: {
       russian: "Кашляющий",
       hindi: "खांसी",
       german: "Husten",
       punjabi: "ਖਾਂਸੀ",
       tamil: "இருமல்",
       bengali: "কাশি",
       gujrati: "કફ",
       kannada: "ಹುಚ್ಚು",
       urdu: "کھانسی",
       malayalam: "ചുമ",
       french: "Toux",
       spanish: "Tos",
       dutch: "Hoesten",
       portuguese: "Tosse",
       telugu: "దగ్గు",
     },
   },
    {
      imgsource: require("../assets/Disease/itching.png"),
      engName: "Itchiness",
      translations: {
        russian: "Зуд",
        hindi: "खुजली",
        german: "Juckreiz",
        punjabi: "ਖੁਜਲੀ",
        tamil: "சுவருக்கம்",
        bengali: "খুজলি",
        gujrati: "ખુંજુઆત",
        kannada: "ಕಿಚ್ಚನ್ನು",
        urdu: "کھجلی",
        malayalam: "ചുമ",
        french: "Démangeaisons",
        spanish: "Picazón",
        dutch: "Jeuk",
        portuguese: "Coceira",
        telugu: "చల్లని",
      },
    },
    {
      imgsource: require("../assets/Disease/back-pain.png"),
      engName: "Back Pain",
      translations: {
        russian: "Боль в спине",
        hindi: "कमर में दर्द",
        german: "Rückenschmerzen",
        punjabi: "ਪਿੱਠ ਦਰਦ",
        tamil: "மீன்குஞ்சு வலி",
        bengali: "পিঠ ব্যথা",
        gujrati: "પીઠનો દુખાવો",
        kannada: "ಹಿಂಗುಡುವಿನ ನೋವು",
        urdu: "پیٹھ درد",
        malayalam: "പിന്നീട് നൊണക്ക്",
        french: "Mal de dos",
        spanish: "Dolor de espalda",
        dutch: "Rugpijn",
        portuguese: "Dor nas costas",
        telugu: "వెనుకబడి నొప్పి",
      },
    },
    {
      imgsource: require("../assets/Disease/joint-pain.png"),
      engName: "Joint Pain",
      translations: {
        russian: "Боль в суставах",
        hindi: "घुटनो का दर्द",
        german: "Gelenkschmerzen",
        punjabi: "ਜੋਰ ਦਰਦ",
        tamil: "கூட்டு வலி",
        bengali: "যৌবন ব্যথা",
        gujrati: "જોડનો દુખાવો",
        kannada: "ಕುಡುಕು ನೋವು",
        urdu: "جوڑوں کا درد",
        malayalam: "ചെരുവകൾ നൊണക്ക്",
        french: "Douleur articulaire",
        spanish: "Dolor articular",
        dutch: "Gewrichtspijn",
        portuguese: "Dor nas articulações",
        telugu: "సంయుక్త నొప్పి",
      },
    },
    {
      imgsource: require("../assets/Disease/period-pain.png"),
      engName: "Period Pain",
      translations: {
        hindi: "पीरियड दर्द",
        russian: "Боль при менструации",
        german: "Regelschmerzen",
        punjabi: "ਮਹੀਨੇ ਦਾ ਦਰਦ",
        tamil: "பெரியம் வலி",
        bengali: "পেরিয়ড ব্যথা",
        gujrati: "મહિનાનો દુખાવો",
        kannada: "ಮಾಸಿಕ ನೋವು",
        urdu: "ماہواری درد",
        malayalam: "പെരിയം നൊണക്ക്",
        french: "Douleur menstruelle",
        spanish: "Dolor menstrual",
        dutch: "Menstruatiepijn",
        portuguese: "Dor menstrual",
        telugu: "రోజులు వేసే నొప్పు",
      },
    },
    {
      imgsource: require("../assets/Disease/headache.png"),
      engName: "Headache",
      translations: {
        hindi: "सिरदर्द",
        russian: "головная боль",
        german: "Kopfschmerzen",
        punjabi: "ਸਿਰ ਦਰਦ",
        tamil: "தலைவலி",
        bengali: "মাথাব্যথা",
        gujrati: "માથાનો દુખાવો",
        kannada: "ತಲೆನೋವು",
        urdu: "سردرد",
        malayalam: "തല നൊണക്ക്",
        french: "Maux de tête",
        spanish: "Dolor de cabeza",
        dutch: "Hoofdpijn",
        portuguese: "Dor de cabeça",
        telugu: "తల నొప్పు",
      },
    },
  
   {
     imgsource: require('../assets/Disease/toothache.png'),
     engName: "Toothache",
     translations: {
       hindi: "दांत का दर्द",
       german: "Zahnweh",
       russian: "Зубная боль",
       punjabi: "ਦੰਦ ਦਰਦ",
       tamil: "பட்டம் வலி",
       bengali: "দন্ত ব্যথা",
       gujrati: "દાંતમાં દુખાવો",
       kannada: "ಪಂಜನ್ನಿ ನೋವು",
       urdu: "دانت درد",
       malayalam: "പല്ല് നൊണക്ക്",
       french: "Douleur dentaire",
       spanish: "Dolor de dientes",
       dutch: "Tandpijn",
       portuguese: "Dor de dente",
       telugu: "దంతమూలం",
     },
   },
 ];
 
 export default Diseasedb;
 